### ISSUE TITLE
analyze-sales

### ISSUE THREAD

**Issue by viramatiiash** [viramatiiash/hope-project#7]
Зверстати блок 'Analyze your sales and marketing leads' на сторінці Home.

**Comment by JuliaTymoshko** [comment]
1. Make sure the icon work well
2. Link the icons properly (via icons mixin & SVG)
3. Pay attention that icons are coloured 
4. Make sure the content is correct
5. Discover More - add the gradient
6. Check missing colours with new variables
7. Add ALT attribute to all pictures

**Comment by JuliaTymoshko** [comment]
- [ ] make it mobile responsive
